### ISSUE TITLE
default to master if no branches are specified

### ISSUE THREAD

**Issue by laneysmith** [austinmckinley/electron-gitlab-ci-monitor#5]
it looks like when you don't specify any branches for a project it is returning the status of the most recent build, irrespective of what branch its on. do we want this behavior or should it default to most recent master build? at the very least, we should probably display the branch name on the project cards.

**Comment by austinmckinley** [comment]
I think I'm going to leave this as is, although the branch feature can probably use another iteration. What would be nice is to have branches optionally be a regexp instead of an array of string literals.

But until then, I think having the option to display all builds regardless of branch is fine default behavior.
